# generated by datamodel-codegen:
#   filename:  testomat-api.yaml
#   timestamp: 2026-02-04T13:28:36+00:00

from typing import Any

from pydantic import BaseModel, Extra, Field


class Attributes(BaseModel):
    class Config:
        extra = Extra.forbid

    url: str | None = Field(None, description="Jira Issue url")
    attachables: list[str] | None = Field(None, description="List of linked to the JiraIssue objects")
    created_at: str | None = Field(None, alias="created-at", description="Date of the JiraIssue creation")
    updated_at: str | None = Field(None, alias="updated-at", description="Last time the JiraIssue was updated")


class JiraIssues(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(..., description="JiraIssue id")
    attributes: Attributes | None = None


class Attributes1(BaseModel):
    class Config:
        extra = Extra.forbid

    tests_ids: list[str] | None = Field(
        None, alias="tests-ids", description="List of tests (require :detail in params)"
    )
    jira_issues: list[str] | None = Field(None, alias="jira-issues", description="List of assigned jira issues")
    created_at: str | None = Field(None, alias="created-at", description="Date of the Plan creation")


class Plans(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(..., description="Plan id")
    attributes: Attributes1 | None = None


class Attributes2(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str = Field(..., description="rungroup title")
    kind: str = Field(..., description="Must be one from [build, sprint, release]")
    emoji: str | None = None
    description: str | None = None
    status: str | None = None
    merge_strategy: str = Field(..., description="Must be one from [realistic, optimistic, pessimistic]")
    runs_count: float | None = Field(None, description="Count of runs")
    passed: float | None = None
    skipped: float | None = None
    failed: float | None = None
    created_at: str | None = Field(None, alias="created-at")
    updated_at: str | None = Field(None, alias="updated-at")
    finished_at: str | None = Field(None, alias="finished-at")
    is_root: bool | None = Field(None, alias="is-root", description="Is this rungroup root node")


class Relationships(BaseModel):
    class Config:
        extra = Extra.forbid

    tests: dict[str, Any] | None = Field(None, description="List of tests")
    children: dict[str, Any] | None = Field(None, description="Child rungroups")
    runs: dict[str, Any] | None = Field(None, description="Include runs")


class Rungroup(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(..., description="rungroup id")
    attributes: Attributes2 | None = None
    relationships: Relationships | None = None


class Attributes3(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str | None = Field(None, description="run title")
    status: str | None = None
    multienv: bool | None = None
    checklist: bool | None = None
    access: str | None = None
    to_url: str | None = Field(None, description="URL of a run")
    env: list[str] | None = None
    passed: float | None = None
    skipped: float | None = None
    failed: float | None = None
    has_finished: bool | None = Field(None, alias="has-finished")
    jira_issues: list[str] | None = Field(None, alias="jira-issues", description="List of assigned jira issues")
    created_at: str | None = Field(None, alias="created-at")
    updated_at: str | None = Field(None, alias="updated-at")
    finished_at: str | None = Field(None, alias="finished-at")
    comments_count: float | None = Field(None, description="Number of comments on the run")


class Relationships1(BaseModel):
    class Config:
        extra = Extra.forbid

    tests: dict[str, Any] | None = Field(None, description="List of tests")
    children: dict[str, Any] | None = Field(None, description="Child suites")


class Run(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(..., description="run id")
    attributes: Attributes3 | None = None
    relationships: Relationships1 | None = None


class Attributes4(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str | None = Field(None, description="Step title")
    descriprion: str | None = Field(None, description="Step description")
    kind: str | None = Field(None, description="Kind manual or automated")
    is_snippet: bool | None = Field(None, description="Is step using as snippet")
    keywords: str | None = Field(None, description="Keywords of step")
    usage_count: float | None = Field(None, description="Counter of step usage in tests")
    created_at: str | None = Field(None, alias="created-at", description="Date of the step creation")
    updated_at: str | None = Field(None, alias="updated-at", description="Last time the step was updated")
    comments_count: float | None = Field(None, description="Number of comments on the step")


class Step(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(..., description="Step id")
    attributes: Attributes4 | None = None


class Attributes5(BaseModel):
    class Config:
        extra = Extra.forbid

    suite_id: str = Field(..., alias="suite-id", description="Suite Id")
    title: str | None = Field(None, description="suite title")
    descriprion: str | None = Field(None, description="suite description")
    code: str | None = Field(None, description="Source code of an automated test")
    file: str | None = Field(None, description="File of an automated test")
    fullpath: str | None = Field(None, description="FutureFile full path")
    file_type: str | None = Field(None, alias="file-type", description="File of an automated test")
    to_url: str | None = Field(None, description="Full url of a suite")
    tags: list[str] | None = Field(None, description="List of tags")
    test_count: float | None = Field(None, alias="test-count")
    tests: list[str] | None = None
    children: list[str] | None = None
    created_at: str | None = Field(None, alias="created-at")
    updated_at: str | None = Field(None, alias="updated-at")
    comments_count: float | None = Field(None, description="Number of comments on the suite")


class Relationships2(BaseModel):
    class Config:
        extra = Extra.forbid

    children: dict[str, Any] | None = Field(None, description="Child suites")


class Suite(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(..., description="suite id")
    attributes: Attributes5 | None = None
    relationships: Relationships2 | None = None


class Attributes6(BaseModel):
    class Config:
        extra = Extra.forbid

    suite_id: str = Field(..., alias="suite-id", description="Suite Id")
    title: str | None = Field(None, description="Test title")
    descriprion: str | None = Field(None, description="Test description")
    state: str | None = Field(None, description="State of string")
    code: str | None = Field(None, description="Source code of an automated test")
    file: str | None = Field(None, description="File of an automated test")
    sync: bool | None = Field(None, description="Is test sycnhronized")
    to_url: str | None = Field(None, description="URL of a test")
    tags: list[str] | None = Field(None, description="List of tags")
    has_examples: bool | None = Field(None, alias="has-examples", description="Is test parametrized?")
    params: list[str] | None = Field(None, description="Parameters of tests")
    run_statuses: list[str] | None = Field(None, alias="run-statuses", description="Last run statuses")
    attachments: list[str] | None = Field(None, description="List of attachments")
    jira_issues: list[str] | None = Field(None, alias="jira-issues", description="List of assigned jira issues")
    assigned_to: str | None = Field(None, alias="assigned-to", description="A user assigned to this test")
    created_by: str | None = Field(None, alias="created-by", description="A user created test")
    created_at: str | None = Field(None, alias="created-at", description="Date of the test creation")
    updated_at: str | None = Field(None, alias="updated-at", description="Last time the test was updated")
    comments_count: float | None = Field(None, description="Number of comments on the test")


class Test(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(..., description="Test id")
    type: str = Field(..., description='must be "test"')
    attributes: Attributes6 | None = None


class Attributes7(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str | None = Field(None, description="test title")
    status: str | None = None
    message: str | None = None
    stack: str | None = None
    steps: dict[str, Any] | None = None
    run_time: float | None = None
    created_at: str | None = Field(None, alias="created-at")
    updated_at: str | None = Field(None, alias="updated-at")
    finished_at: str | None = Field(None, alias="finished-at")


class Testrun(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(..., description="test run id")
    attributes: Attributes7 | None = None


class Attributes8(BaseModel):
    class Config:
        extra = Extra.forbid

    jira_urls: list[str] = Field(..., description="List of JiraIssue urls")
    attachables: list[str] = Field(..., description="List of linked to the JiraIssue objects")


class Jiraissues(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(..., description="JiraIssue id")
    attributes: Attributes8
